@echo off
echo Cleaning up Next.js build files and regenerating Prisma client...

echo Stopping any running servers...
taskkill /f /im node.exe /t 2>nul

echo Removing .next directory...
rmdir /s /q ".next" 2>nul

echo Removing node_modules/.prisma directory...
rmdir /s /q "node_modules\.prisma" 2>nul

echo Removing node_modules/@prisma directory...
rmdir /s /q "node_modules\@prisma" 2>nul

echo Regenerating Prisma client...
call npx prisma generate

echo Running Next.js dev server...
call npm run dev

echo Done.
