@echo off
echo Stopping any running Node processes...
taskkill /f /im node.exe 2>nul

echo Clearing Prisma cache...
rmdir /s /q node_modules\.prisma 2>nul

echo Generating Prisma client...
npx prisma generate

echo Starting development server...
npm run dev
